### PR TITLE
Collab File Structure

### PR DESCRIPTION
**Pull request by B1910668-TN**
Hi, I have completed the issue. You can check it. =)

### CODE REVIEW

**Review by Medic1111 — CHANGES_REQUESTED** [review]
Awesome Job!... Just one thing missing:
- [ ] both files you created should be nested inside a FOLDER called Collab.

Thanks again for your time =)

**Comment by Medic1111** [comment]
HEYYYYY....ACTUALLY THAT WAS MY MISTAKE. You followed all steps appropriately! Unfortunately I miss-typed the name of the folder... It shouldn't be Modal... but rather Collab.

**Comment by B1910668-TN** [comment]
> HEYYYYY....ACTUALLY THAT WAS MY MISTAKE. You followed all steps appropriately! Unfortunately I miss-typed the name of the folder... It shouldn't be Modal... but rather Collab.

I renamed the Modal folder to Collab =)

**Review by Medic1111 — APPROVED** [review]

**Comment by Medic1111** [comment]
Awesome! Thank you so much! MERGED

**Pull request merged**
